# Generated by Django 2.0.9 on 2018-10-16 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Handler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitterhandle', models.CharField(max_length=500)),
                ('follower', models.IntegerField()),
                ('following', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Handler',
            },
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tweet', models.CharField(max_length=280)),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='handler',
            name='toptweets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tweets'),
        ),
    ]
