# Generated by Django 2.0.9 on 2018-10-18 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181016_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handler',
            name='tweets',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Tweets'),
        ),
        migrations.AlterField(
            model_name='handler',
            name='twitterhandle',
            field=models.CharField(max_length=100),
        ),
    ]
