# Generated by Django 2.0.9 on 2018-10-18 21:16

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181018_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='handler',
            name='tweetcount',
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True),
        ),
    ]
